### ISSUE TITLE
ToDo v3

### ISSUE THREAD

**Issue by pierreguillot** [CICM/HoaLibrary-Light#2]
- [ ] change the license to GPL v2 ?
- [ ] encoder: improve for 1st, 2nd & 3rd orders at least
- [ ] optim: check the Max-Re 2d and 3d

**Comment by olilarkin** [comment]
what are the issues with the encoder?

**Comment by pierreguillot** [comment]
No it's just optimization and I remember that's I've already done the job (need to check).

**Comment by olilarkin** [comment]
thanks pierre
